import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import './styles.css';

const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:9292/api';
const COMMERCE=import.meta.env.VITE_COMMERCE_API_URL||'http://localhost:9191/api';
function App(){
 const [filters,setFilters]=useState({collection:'',size:'',finish:'',color:'',maxProducts:30});
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(new Set()),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [token,setToken]=useState(''),[shopId,setShopId]=useState(''),[price,setPrice]=useState({}),[stock,setStock]=useState({});
 const update=(k,v)=>setFilters({...filters,[k]:v});
 async function fetchProducts(){setLoading(true);setError('');try{const r=await axios.post(`${API}/anjani/fetch`,filters);setRows(r.data);setSelected(new Set())}catch(e){setError(e.response?.data?.message||e.message||'Fetch failed')}finally{setLoading(false)}}
 async function downloadCsv(){try{const r=await axios.post(`${API}/anjani/csv`,filters,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='anjani-products.csv';a.click();URL.revokeObjectURL(url)}catch(e){setError(e.message)}}
 const toggle=k=>setSelected(s=>{const n=new Set(s);n.has(k)?n.delete(k):n.add(k);return n});
 async function push(){const chosen=rows.filter(p=>selected.has(p.importKey)).map(p=>({...p,basePrice:Number(price[p.importKey]||1),discountPrice:null,taxPercentage:0,minimumOrderQuantity:1,unit:'box',stockQuantity:Number(stock[p.importKey]||0)}));if(!chosen.length)return setError('Select at least one product.');if(!shopId||!token)return setError('Enter the shop ID and JWT from the Tile Commerce shop-owner login.');setLoading(true);try{const r=await axios.post(`${COMMERCE}/products/import/anjani`,{shopId:Number(shopId),products:chosen},{headers:{Authorization:`Bearer ${token}`}});alert(`Imported. Created ${r.data.created}, updated ${r.data.updated}.`)}catch(e){setError(e.response?.data?.message||e.message||'Import failed')}finally{setLoading(false)}}
 return <div className="page"><header><div><h1>Anjani Tek Live Product Catalog</h1><p>Live Anjani public catalogue → select → import into your Tile Commerce shop</p></div></header>
 <section className="panel"><div className="grid"><label>Collection<input value={filters.collection} onChange={e=>update('collection',e.target.value)} placeholder="e.g. GVT Collections"/></label><label>Size<input value={filters.size} onChange={e=>update('size',e.target.value)} placeholder="e.g. 600x600mm"/></label><label>Finish<input value={filters.finish} onChange={e=>update('finish',e.target.value)} placeholder="e.g. Glossy Surface"/></label><label>Color<input value={filters.color} onChange={e=>update('color',e.target.value)} placeholder="e.g. BLACK"/></label><label>Max products<input type="number" min="1" max="200" value={filters.maxProducts} onChange={e=>update('maxProducts',Number(e.target.value))}/></label></div><div className="actions"><button onClick={fetchProducts} disabled={loading}>{loading?'Fetching...':'Fetch from Anjani Tek'}</button><button className="secondary" onClick={downloadCsv} disabled={loading}>Download Live CSV</button></div></section>
 <section className="panel"><div className="grid"><label>Tile Commerce Shop ID<input value={shopId} onChange={e=>setShopId(e.target.value)} placeholder="From shop-register/login response"/></label><label className="wide">JWT token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Bearer token value only"/></label></div></section>
 {error&&<div className="error">{String(error)}</div>}<div className="summary">Products fetched: <b>{rows.length}</b> · Selected: <b>{selected.size}</b><button className="push" onClick={push} disabled={!selected.size||loading}>Import Selected To Tile Commerce</button></div>
 <section className="cards">{rows.map((p,i)=><article className="card" key={p.importKey||i}>{p.imageUrl?<img src={p.imageUrl} alt={p.name} onError={e=>e.currentTarget.style.display='none'}/>:<div className="noimg">No image</div>}<div className="body"><div><input type="checkbox" checked={selected.has(p.importKey)} onChange={()=>toggle(p.importKey)}/> Select</div><h3>{p.name}</h3><div className="code">Supplier code: {p.supplierProductCode||'—'}</div><div className="chips"><span>{p.collection||'—'}</span><span>{p.size||'—'}</span><span>{p.finish||'—'}</span><span>{p.color||'—'}</span></div>{selected.has(p.importKey)&&<><input type="number" min="0.01" placeholder="Selling price" value={price[p.importKey]||''} onChange={e=>setPrice({...price,[p.importKey]:e.target.value})}/><input type="number" min="0" placeholder="Opening stock" value={stock[p.importKey]||''} onChange={e=>setStock({...stock,[p.importKey]:e.target.value})}/></>}<a href={p.detailUrl} target="_blank" rel="noreferrer">Open source product</a></div></article>)}</section></div>
}
createRoot(document.getElementById('root')).render(<App/>);
