import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, CreditCard, MapPin, PackageCheck } from 'lucide-react'
import api from '../api/axiosClient'

export default function Checkout(){
 const [addresses,setAddresses]=useState([]),[selected,setSelected]=useState(''),[form,setForm]=useState({addressLine1:'',addressLine2:'',city:'',state:'',postalCode:'',country:'India',phoneNumber:'',defaultAddress:true}),[order,setOrder]=useState(null),[ref,setRef]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 const nav=useNavigate()
 useEffect(()=>api.get('/addresses').then(r=>{setAddresses(r.data||[]);const d=(r.data||[]).find(x=>x.defaultAddress);if(d)setSelected(String(d.id))}).catch(e=>setErr(e.response?.data?.message||'Unable to load addresses.')),[])
 const setField=(k,v)=>setForm(x=>({...x,[k]:v}))
 const saveAddress=async()=>{const r=await api.post('/addresses',form);setAddresses(x=>[...x,r.data]);setSelected(String(r.data.id));return r.data.id}
 const checkout=async()=>{setBusy(true);setErr('');try{const addressId=selected||await saveAddress();const r=await api.post('/orders/checkout',{addressId:Number(addressId)});setOrder(r.data)}catch(e){setErr(e.response?.data?.message||'Checkout failed.')}finally{setBusy(false)}}
 const pay=async()=>{setBusy(true);setErr('');try{await api.post(`/orders/${order.id}/payment`,{paymentReference:ref});nav('/orders')}catch(e){setErr(e.response?.data?.message||'Payment submission failed.')}finally{setBusy(false)}}
 return <div className="shop-page narrow"><button className="back-link button-link" onClick={()=>nav('/cart')}><ArrowLeft size={15}/> Back to cart</button><div className="section-heading"><div><div className="eyebrow">CHECKOUT</div><h1>{order?'Payment submission':'Complete your order'}</h1><p>{order?'Your order is created and awaiting payment verification.':'Choose a delivery address and place your order.'}</p></div></div>
 {err&&<div className="form-alert error">{err}</div>}
 {!order?<div className="checkout-layout"><section className="checkout-card"><h2><MapPin size={18}/> Delivery address</h2>{addresses.length>0&&<div className="address-options">{addresses.map(a=><button className={`address-option ${String(a.id)===String(selected)?'selected':''}`} key={a.id} onClick={()=>setSelected(String(a.id))}><strong>{a.addressLine1}</strong><span>{a.city}, {a.state} {a.postalCode}</span>{a.defaultAddress&&<em>Default</em>}</button>)}</div>}
 <div className="new-address"><h3>{addresses.length?'Add another address':'Enter delivery address'}</h3><div className="modern-form two-col"><label className="span-2">Address line 1<input value={form.addressLine1} onChange={e=>setField('addressLine1',e.target.value)}/></label><label className="span-2">Address line 2<input value={form.addressLine2} onChange={e=>setField('addressLine2',e.target.value)}/></label><label>City<input value={form.city} onChange={e=>setField('city',e.target.value)}/></label><label>State<input value={form.state} onChange={e=>setField('state',e.target.value)}/></label><label>Postal code<input value={form.postalCode} onChange={e=>setField('postalCode',e.target.value)}/></label><label>Phone<input value={form.phoneNumber} onChange={e=>setField('phoneNumber',e.target.value)}/></label></div></div></section><aside className="summary-card"><h3>Ready to place order?</h3><p>Stock is checked again by the backend during checkout.</p><button className="wide-primary" onClick={checkout} disabled={busy}>{busy?'Creating order…':<>Place order <PackageCheck size={16}/></>}</button></aside></div>
 :<div className="payment-card"><div className="success-mark"><CheckCircle2 size={32}/></div><div className="eyebrow">ORDER CREATED</div><h2>{order.orderNumber}</h2><p>Grand total: <strong>₹ {Number(order.grandTotal).toLocaleString('en-IN')}</strong></p><div className="payment-instructions"><CreditCard size={20}/><div><strong>Submit your payment reference</strong><span>Enter your UPI / bank payment reference. A shop owner will verify the payment before the invoice is issued.</span></div></div><label className="payment-field">Payment reference<input value={ref} onChange={e=>setRef(e.target.value)} placeholder="e.g. UPI transaction reference"/></label><button className="wide-primary" disabled={!ref.trim()||busy} onClick={pay}>{busy?'Submitting…':'Submit payment reference'}</button></div>}
 </div>
}
